### ISSUE TITLE
Sign up approval function

### ISSUE THREAD

**Issue by dongs0** [fosslight/fosslight#233]
**Is your feature request related to a problem? Please describe.**
Currently, in FOSSLight, the admin does not have the ability to approve new subscribers, so it is very difficult to manage the account.

**Describe the solution you'd like**
I hope that there is a function that requires the consent of the admin to complete the registration.

**Comment by soimkim** [comment]
@dongs0 ,
The LDAP function can be utilized to allow only specific users to log in and use.
And when a user joins, he or she joins as a general user, and division for each user can also be set.

Therefore, there is no plan to add an additional approval procedure for user registration, so this issue is closed.

**Comment by dongs0** [comment]
Sorry I missed the comment.
We are let's try LDAP integration.
