### ISSUE TITLE
fosslight project store unrelated folder 

### ISSUE THREAD

**Issue by namkyu1999** [fosslight/fosslight#30]
**Describe the bug**
When we excute docker-compose for starting this project,
docker-compose automatically generate db folder(for mariadb) and web-data folder(for web) .
That folders are unreleated to project because They are personal data.
So we have to ignore that folders.

**To Reproduce**
Add folders name to .gitignore

**Comment by riyenas0925** [comment]
@namkyu1999 
I also experienced the same symptoms!

However, it would be better to exclude only the db/data/ folder than to exclude the entire /db folder.

This is because "db/initb.d/fosslight_create.sql" is required to initialize the database when running docker-compose. There is also a mysql configuration file in the "db/conf.d/.." folder.

**Comment by namkyu1999** [comment]
I think you're right!
I will edit the code to reflect your comments

**Comment by soimkim** [comment]
Dear @namkyu1999 ,
How about changing the label to chore?
This issue seems to be a chore, not a bug, what do you think?

**Comment by namkyu1999** [comment]
I think so
But I dont't have permission to change labels. Is there any way to change labels @soimkim ?

**Comment by soimkim** [comment]
I changed the label. 
I'll try to find some github permissions.
