### ISSUE TITLE
split javascript library 

### ISSUE THREAD

**Issue by darjeeling** [fosslight/fosslight#452]
**Is your feature request related to a problem? Please describe.**
in repository, there is some javascript library which has different license.

**Describe the solution you'd like**
so IMHO, need to split these and download it to specific directory when build runs

**Describe alternatives you've considered**

**Additional context**
this behavior can break license. so be careful

**Comment by soimkim** [comment]
Would you tell me which javascript library you are talking about?
And why are these libraries downloaded and built in a specific directory?

Please understand that I am asking a question because I am not familiar with it.

**Comment by darjeeling** [comment]
@soimkim 
for example [in static javascript directory](https://github.com/fosslight/fosslight/tree/develop/src/main/resources/static/js)
has mixed of own script and multiple library which was imported to frozen by developer.

it has several problem

1. license problem - some license can't be mixed within source code. but if you build it. it's ok
2. security problem - as this code dose not have version in the source. can't get the problem when some security problem happened. 

so need to get the javascript and some css at the build time  with specific version

**Comment by soimkim** [comment]
Thanks for the details.
That's an important point from the point of view of security vulnerabilities.

**Comment by soimkim** [comment]
@darjeeling , Customized libs such as jqgrid, editor, and alertify seem difficult to apply. 😢

**Comment by darjeeling** [comment]
@soimkim it's ok. 
starting is important
1. itemize libs
2. apply possible things
3. mark left stuff

**Comment by soimkim** [comment]
https://github.com/fosslight/fosslight/pull/814/commits/dbf08b5228536ad4140eb22ec92a26f44406149f : Changed the applicable libs to CND within the scope of low risk.

Reason for excluding **ckeditor** and **jqgrid**: It is impossible for jqgrid because there are custom parts, and in the case of ckeditor, cdn is provided only for core files, so plugins and related files must be applied the same as before.
The two libs are excluded because of the high risk.
