### ISSUE TITLE
Self-check > Pop-up when requesting analysis after entering the URL in Self-check

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#915]
Self-check > Self-check에서 URL 입력 후 분석 요청시 팝업
- request가 정상적으로 간 경우 Successfully completed 팝업 우측 하단에 띄우기
- request 실패시 system 에러 팝업 우측 하단에 띄우기

Self-check > Pop-up when requesting analysis after entering the URL in Self-check
- If the request goes normally, display the Successfully completed pop-up on the lower right corner
- In case of request failure, display system error pop-up on the lower right corner

**Comment by yenawee** [comment]
Hello , I think this feature appears to be already implemented.

I didn't see a popup on success because I didn't know the URL address that succeeded, but I did see a popup on the bottom right that failed when I put in an invalid URL.
<img width="700" alt="스크린샷 2023-07-28 오후 8 03 57" src="https://github.com/fosslight/fosslight/assets/91937954/08a72a1c-9b6a-4e7e-be07-9a88fdab72b5">


The relevant code is located in the 

`main.webapp.WEB_INF.view.admin.selfCheck.edit-js.jsp`.
<img width="700" alt="스크린샷 2023-07-28 오후 8 01 31" src="https://github.com/fosslight/fosslight/assets/91937954/374bcd9e-9f54-48de-9acf-581ea2abce9a">

Am I misunderstanding this issue?

Any answers would be appreciated.

**Comment by soimkim** [comment]
@yenawee , 해당 이슈 이미 구현되어 있는 건으로 close합니다.
확인 감사합니다. 👍
